# Generated by Django 5.1.3 on 2024-11-28 00:34

import inventory.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", inventory.models.CustomUserManager()),
            ],
        ),
    ]
